version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
  zookeeper1:
    image: wurstmeister/zookeeper
    container_name: zookeeper1
    ports:
      - "12181:2181"
    networks:
      vpcbr:
        ipv4_address: 10.5.1.2
  zookeeper2:
    image: wurstmeister/zookeeper
    container_name: zookeepe2
    ports:
      - "22181:2181"
    networks:
      vpcbr:
        ipv4_address: 10.5.2.2
  kafka:
    build: .
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    environment:
      XXXKAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      XXXKAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.91:19092
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  kafka1:
    build: .
    container_name: kafka1
    ports:
      - "19092:9092"
    networks:
      vpcbr:
        ipv4_address: 10.5.1.3
    environment:
      XXXKAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      XXXKAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.91:19092
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 19092
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper1
  kafka2:
    build: .
    container_name: kafka2
    ports:
      - "29092:9092"
    networks:
      vpcbr:
        ipv4_address: 10.5.2.3
    environment:
      XXXKAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      XXXKAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.91:19092
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 29092
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper2
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
