version: '2.1'
services:
  zookeeper-multi:
    image: wurstmeister/zookeeper
    container_name: zookeeper-multi
    ports:
      - "2181:2181"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    healthcheck:
        test: ["CMD", "sleep", "3"]
        interval: 3s
        timeout: 4s
        retries: 3
  kafka-1:
    build: .
    container_name: kafka-1
    ports:
      - "9092:9092"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-multi:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      zookeeper-multi:
        condition: service_healthy
    healthcheck:
        test: ["CMD", "sleep", "3"]
        interval: 3s
        timeout: 4s
        retries: 3
  kafka-2:
    build: .
    container_name: kafka-2
    ports:
      - "19092:9092"
    networks:
      vpcbr:
        ipv4_address: 10.5.1.3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 19092
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-multi:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      kafka-1:
        condition: service_healthy
    healthcheck:
        test: ["CMD", "sleep", "3"]
        interval: 3s
        timeout: 4s
        retries: 3
  kafka-3:
    build: .
    container_name: kafka-3
    ports:
      - "29092:9092"
    networks:
      vpcbr:
        ipv4_address: 10.5.2.3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 29092
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-multi:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      kafka-2:
        condition: service_healthy
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
