#!/usr/bin/env bash

export HOST_IP=`ipconfig getifaddr en1`
CONTAINER_NAME=`basename "$0"`
CONTAINER_SEQ=$(echo $CONTAINER_NAME | sed s@[a-zA-Z]@@g)
CONTAINER_ID=$(docker ps -f name=$CONTAINER_NAME --format "{{.ID}}")

echo $HOST_IP, $CONTAINER_ID, $CONTAINER_SEQ

if [[ -z "$CONTAINER_ID" ]]; then
	echo starting $CONTAINER_NAME
	docker-compose up -d kafka
else
	echo stoping $CONTAINER_NAME
	docker stop $CONTAINER_NAME
	docker stop zookeeper$CONTAINER_SEQ
fi


